# Generated by Django 5.0.1 on 2025-07-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_classification_fields'),
        ('suppliers', '0001_initial'),
        ('transporters', '0003_alter_transporter_fleet_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='items_supplied',
            field=models.ManyToManyField(blank=True, help_text='Items that this supplier can provide', related_name='suppliers', to='items.item'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='preferred_transporters',
            field=models.ManyToManyField(blank=True, help_text='Preferred transporters for this supplier', related_name='preferred_by_suppliers', to='transporters.transporter'),
        ),
    ]
