# Generated by Django 5.0.1 on 2025-07-25 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='item',
            name='item_master_classif_806bc0_idx',
        ),
        migrations.RemoveField(
            model_name='item',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='item',
            name='lead_time_days',
        ),
        migrations.RemoveField(
            model_name='item',
            name='maximum_stock',
        ),
    ]
