# Generated by Django 5.0.1 on 2025-07-30 12:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_classification_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_id', models.CharField(editable=False, help_text='Auto-generated Transfer ID', max_length=20, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity being transferred', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('from_location', models.CharField(help_text='Source location', max_length=100)),
                ('to_location', models.CharField(help_text='Destination location', max_length=100)),
                ('transfer_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When the transfer was initiated')),
                ('expected_completion', models.DateTimeField(blank=True, help_text='Expected completion date/time', null=True)),
                ('actual_completion', models.DateTimeField(blank=True, help_text='Actual completion date/time', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the transfer', max_length=15)),
                ('transfer_reason', models.CharField(blank=True, help_text='Reason for the transfer', max_length=200)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks or notes')),
                ('created_by', models.CharField(blank=True, help_text='User who initiated the transfer', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(help_text='Item being transferred', on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='items.item')),
            ],
            options={
                'db_table': 'item_transfers',
                'ordering': ['-transfer_date'],
                'indexes': [models.Index(fields=['status'], name='item_transf_status_11b924_idx'), models.Index(fields=['transfer_date'], name='item_transf_transfe_6fdbf4_idx'), models.Index(fields=['item'], name='item_transf_item_id_a645fd_idx')],
            },
        ),
    ]
