# Generated by Django 5.0.1 on 2025-07-26 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transporter_id', models.CharField(editable=False, help_text='Auto-generated unique transporter ID', max_length=20, unique=True)),
                ('transporter_name', models.CharField(help_text='Official transporter/company name', max_length=200, unique=True)),
                ('contact_person', models.CharField(help_text='Primary contact person name', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending_approval', 'Pending Approval'), ('blacklisted', 'Blacklisted')], default='pending_approval', help_text='Current transporter status', max_length=20)),
                ('phone_number', models.CharField(help_text='Primary phone number', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('alternate_phone', models.CharField(blank=True, help_text='Alternative phone number', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, help_text='Primary email address (optional)', max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('address_line_1', models.CharField(help_text='Street address line 1', max_length=200)),
                ('address_line_2', models.CharField(blank=True, help_text='Street address line 2 (optional)', max_length=200, null=True)),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('state', models.CharField(help_text='State/Province', max_length=100)),
                ('postal_code', models.CharField(help_text='Postal/ZIP code', max_length=20)),
                ('country', models.CharField(default='India', help_text='Country', max_length=100)),
                ('serviceable_locations', models.TextField(help_text='Areas/cities/regions serviceable (comma-separated for multiple locations)')),
                ('primary_vehicle_type', models.CharField(choices=[('truck', 'Truck'), ('mini_truck', 'Mini Truck'), ('tempo', 'Tempo'), ('pickup', 'Pickup'), ('container', 'Container'), ('trailer', 'Trailer'), ('mini_van', 'Mini Van'), ('big_van', 'Big Van'), ('bike', 'Bike/Motorcycle'), ('auto_rickshaw', 'Auto Rickshaw'), ('other', 'Other')], default='truck', help_text='Primary vehicle type', max_length=20)),
                ('fleet_size', models.PositiveIntegerField(default=1, help_text='Number of vehicles in fleet')),
                ('vehicle_details', models.TextField(blank=True, help_text='Additional vehicle details, capacity, specifications (optional)', null=True)),
                ('rate_type', models.CharField(choices=[('per_km', 'Per Kilometer'), ('fixed_rate', 'Fixed Rate'), ('per_ton', 'Per Ton'), ('per_trip', 'Per Trip'), ('negotiable', 'Negotiable')], default='negotiable', help_text='Rate calculation method', max_length=20)),
                ('standard_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Standard rate amount (optional)', max_digits=10, null=True)),
                ('license_number', models.CharField(blank=True, help_text='Transport license number (optional)', max_length=50, null=True)),
                ('registration_number', models.CharField(blank=True, help_text='Business registration number (optional)', max_length=50, null=True)),
                ('gstin', models.CharField(blank=True, help_text='GST Identification Number (15 digits)', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid GSTIN (15 characters)', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')])),
                ('pan_number', models.CharField(blank=True, help_text='PAN Card Number', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid PAN number (e.g., ABCDE1234F)', regex='^[A-Z]{5}[0-9]{4}[A-Z]{1}$')])),
                ('rating', models.CharField(choices=[('excellent', 'Excellent (A+)'), ('good', 'Good (A)'), ('average', 'Average (B)'), ('below_average', 'Below Average (C)'), ('poor', 'Poor (D)'), ('not_rated', 'Not Rated')], default='not_rated', help_text='Transporter performance rating', max_length=20)),
                ('services_offered', models.TextField(blank=True, help_text='Types of transportation services offered (optional)', null=True)),
                ('operational_hours', models.CharField(blank=True, help_text='Operational hours (e.g., 24/7, 9 AM - 6 PM) (optional)', max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Additional notes or comments', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='System', help_text='User who created this transporter', max_length=100)),
            ],
            options={
                'verbose_name': 'Transporter',
                'verbose_name_plural': 'Transporters',
                'db_table': 'transporter_master',
                'ordering': ['transporter_name'],
                'indexes': [models.Index(fields=['status'], name='transporter_status_63a22e_idx'), models.Index(fields=['transporter_name'], name='transporter_transpo_a753b7_idx'), models.Index(fields=['primary_vehicle_type'], name='transporter_primary_931cb8_idx'), models.Index(fields=['created_at'], name='transporter_created_316c24_idx')],
            },
        ),
    ]
