# Generated by Django 5.0.1 on 2025-07-26 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporter',
            name='account_number',
            field=models.CharField(blank=True, help_text='Bank account number (optional)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transporter',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank name (optional)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transporter',
            name='ifsc_code',
            field=models.CharField(blank=True, help_text='IFSC code (optional)', max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid IFSC code (e.g., SBIN0001234)', regex='^[A-Z]{4}0[A-Z0-9]{6}$')]),
        ),
        migrations.AddField(
            model_name='transporter',
            name='upi_scanner_image',
            field=models.ImageField(blank=True, help_text='UPI QR code scanner image (optional)', null=True, upload_to='transporter_upi_scanners/'),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='rate_type',
            field=models.CharField(choices=[('per_km', 'Per Kilometer'), ('per_kg', 'Per Kilogram'), ('fixed_rate', 'Fixed Rate'), ('per_ton', 'Per Ton'), ('per_trip', 'Per Trip'), ('negotiable', 'Negotiable')], default='negotiable', help_text='Rate calculation method', max_length=20),
        ),
    ]
