# Generated by Django 5.0.1 on 2025-07-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporters', '0002_transporter_account_number_transporter_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporter',
            name='fleet_size',
            field=models.PositiveIntegerField(blank=True, help_text='Number of vehicles in fleet (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='primary_vehicle_type',
            field=models.CharField(blank=True, choices=[('truck', 'Truck'), ('mini_truck', 'Mini Truck'), ('tempo', 'Tempo'), ('pickup', 'Pickup'), ('container', 'Container'), ('trailer', 'Trailer'), ('mini_van', 'Mini Van'), ('big_van', 'Big Van'), ('bike', 'Bike/Motorcycle'), ('auto_rickshaw', 'Auto Rickshaw'), ('other', 'Other')], help_text='Primary vehicle type (optional)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='rate_type',
            field=models.CharField(blank=True, choices=[('per_km', 'Per Kilometer'), ('per_kg', 'Per Kilogram'), ('fixed_rate', 'Fixed Rate'), ('per_ton', 'Per Ton'), ('per_trip', 'Per Trip'), ('negotiable', 'Negotiable')], help_text='Rate calculation method (optional)', max_length=20, null=True),
        ),
    ]
