# Generated by Django 5.0.1 on 2025-07-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_classification_fields'),
        ('locations', '0001_initial'),
        ('transporters', '0003_alter_transporter_fleet_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporter',
            name='serviceable_locations',
        ),
        migrations.AddField(
            model_name='transporter',
            name='items_carried',
            field=models.ManyToManyField(blank=True, help_text='Types of items this transporter can carry', related_name='transporters', to='items.item'),
        ),
        migrations.AddField(
            model_name='transporter',
            name='serviceable_districts',
            field=models.ManyToManyField(blank=True, help_text='Districts serviceable by this transporter', related_name='transporters', to='locations.district'),
        ),
        migrations.AddField(
            model_name='transporter',
            name='serviceable_locations_text',
            field=models.TextField(blank=True, help_text='Legacy text field for additional location details (optional)', null=True),
        ),
    ]
