# Generated by Django 5.0.1 on 2025-07-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_city'),
        ('transporters', '0004_remove_transporter_serviceable_locations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporter',
            name='serviceable_districts',
        ),
        migrations.AddField(
            model_name='transporter',
            name='custom_locations',
            field=models.TextField(blank=True, help_text='Custom locations not in the standard city list (optional)', null=True),
        ),
        migrations.AddField(
            model_name='transporter',
            name='serviceable_cities',
            field=models.ManyToManyField(blank=True, help_text='Major cities serviceable by this transporter', related_name='transporters', to='locations.city'),
        ),
    ]
